name: ci

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        pip install -r test-requirements.txt
        pip install .[all]
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov termtables
    - name: Submit to codecov
      # https://github.com/jmoiron/humanize/pull/117
      if: success()
      run: |
        curl -s https://codecov.io/bash -o codecov.sh
        bash codecov.sh -F ${{ matrix.codecov-flag }}
      env:
        CODECOV_NAME: ${{ matrix.os }} Python ${{ matrix.python-version }}
